{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-urlchecker
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/urlchecker_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/urlchecker/urlchecker_{{ version }}.tar.gz
  sha256: 62165ddbe1b748b58c71a50c8f07fdde6f3d19a7b39787b9fa2b4f9216250318

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  # noarch only builds on linux64
  skip: True # [not linux64]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base {{ r_version }}
    - r-cli
    - r-curl
    - r-xml2
  run:
    - r-base {{ r_version }}
    - r-cli
    - r-curl
    - r-xml2

test:
  commands:
    - $R -e "library('urlchecker')"           # [not win]
    - "\"%R%\" -e \"library('urlchecker')\""  # [win]

about:
  home: https://github.com/r-lib/urlchecker
  license: GPL-3.0-only
  summary: Provide the URL checking tools available in R 4.1+ as a package for earlier versions
    of R. Also uses concurrent requests so can be much faster than the serial versions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-devtools"
    recipe-maintainers:
      - bkreider

